// <auto-generated />
namespace TEST_EVERYTHING.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddData3Rows : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddData3Rows));
        
        string IMigrationMetadata.Id
        {
            get { return "201608301247102_AddData3Rows"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
